name: Publish Docker image

on:
  push:
    branches:    
      - master
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true 
        default: 'dev' 
        type: choice
        options:
        - dev

env:
  TAG: ${{ inputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build Docker image
      run: |
        : "${TAG:=$(date +"%Y.%U.%u")}"
        echo "TAG=$TAG" >> $GITHUB_ENV
    - name: Build Docker image
      run: docker build . --file ./setup/Dockerfile --tag devonfwforge/hangar:$TAG
    - name: Push Docker image
      run: docker push devonfwforge/hangar:$TAG
